### ISSUE TITLE
Global DispatchQueue 의 Qos 에는 어떤 종류가 있는지, 각각 어떤 의미인지 설명하시오.

### ISSUE THREAD

**Issue by zekexros** [huequad/interview#2]

**Comment by zekexros** [comment]
https://velog.io/@zeke/whatsDispatchQueueQoS

**Comment by lenaios** [comment]
main queue와 달리 global queue에 접근할 때는 `DispatchQoS`를 파라미터로 넘길 수 있는데,
DispatchQoS는 실행 우선 순위를 의미한다.
The quality of service, or the execution priority, to apply to tasks.
 
- DispatchQoS.userInteractive : high priority, only do something short and quick
- DispatchQoS.userInitiated : high priority, but might take a little bit of time
- DispatchQoS.default : default quality-of-service class
- DispatchQoS.utility : long-running background processes, low priority
- DispatchQoS.background : not directly initiated by user, so can run as slow as needed

https://velog.io/@lena_/Concurrency-Programming
